name: Create Repo from Template

on:
  issues:
    types: [opened]

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Create repo from template
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/ORG/TEMPLATE_REPO/generate \
          -d '{
            "name": "novo-repo",
            "private": true
          }'